steps:
    - commands:
          - "swift build"
          - "swift test"
          # - "xcodebuild -scheme 'SwiftDocTest' -allowProvisioningUpdates -destination 'generic/platform=macOS'"
          # - "xcodebuild -scheme 'SwiftDocTest' -allowProvisioningUpdates -destination 'generic/platform=iOS'"
