steps:
  - commands:
      - "swift build"
      - "swift test --enable-code-coverage"
      # - "xcodebuild -scheme 'SwiftDocTest' -allowProvisioningUpdates -destination 'generic/platform=macOS'"
      # - "xcodebuild -scheme 'SwiftDocTest' -allowProvisioningUpdates -destination 'generic/platform=iOS'"
